In [1]:
import numpy as np
x = np.array([3, 4, 5])
np.vander(x)
print(np.vander(x))
np.vander(x, increasing=False)

[[ 9  3  1]
 [16  4  1]
 [25  5  1]]


array([[ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [2]:
import numpy as np
x = np.array([3, 4, 5])
np.vander(x)
print(np.vander(x))
np.vander(x, increasing=True)

[[ 9  3  1]
 [16  4  1]
 [25  5  1]]


array([[ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])